### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by shinrenpan** [kelp404/NyaruDB#1]
我在一個IBAction 執行insertDocument 就crash了

**Comment by kelp404** [comment]
Hi, @shinrenpan ,
Do you `createCollection` before insert documents?

There are some example code in the tests:
https://github.com/Kelp404/NyaruDB/blob/master/NyaruDB/NyaruDBTests/NyaruDBTests.m

The new version will be release in 7 days.

**Comment by shinrenpan** [comment]
###開發環境 iOS 6.0 MRC

```
- (void)viewDidLoad
{
  [super viewDidLoad];
   NyaruDB *db = [NyaruDB sharedInstance];
  self.collection = [db collectionForName:@"Test"];

  if(!_collection)
  {
    self.collection = [db createCollection:@"Test"];
  }
}
```

Always crash here

```
//Click to insert
- (IBAction)insertToDB:(id)sender
{
  [_collection insertDocument:@{@"Hello" : @"World"}];
}
```

**Comment by kelp404** [comment]
Hello,

Is `self.collection` equal `_collection` in your code?

It didn't crash in the code.

``` Objective-C
NyaruDB *db = [NyaruDB sharedInstance];
NyaruCollection *collection = [db collectionForName:@"Test"];
if (!collection)
{
    collection = [db createCollection:@"Test"];
}
[collection insertDocument:@{@"Hello" : @"World"}];
```

Could you check unit test successful in your Mac?
Project -> Test
