### ISSUE TITLE
Memory problem since "NyaruDB use memory cache, GCD and binary tree to optimize performance."

### ISSUE THREAD

**Issue by steve21124** [kelp404/NyaruDB#11]
using memory cache for database of 160 thousands record. it use almost 200mb+ memory. Is there a way not using memory cache?

**Comment by kelp404** [comment]
Hello @steve21124 ,

You could change `NYARU_CACHE_LIMIT`.
https://github.com/kelp404/NyaruDB/blob/master/NyaruDB/NyaruDB/NyaruConfig.h#L16

**Comment by steve21124** [comment]
using the code "NyaruDBDemoViewController.m"

change inserting to 200 thousands record and after finished inserting. the memory still stay at 400MB and not going down even after using [collection clearCache]; and "#define NYARU_CACHE_LIMIT 1".

``` objective-c
    NSDate *timer = [NSDate date];
    for (NSInteger loop = 0; loop < 200000; loop++) {
        [doc setObject:[NSNumber numberWithInt:arc4random() % 512] forKey:@"group"];
        [collection put:doc];
    }
    NSLog(@"------------------------------------------------");
    NSLog(@"insert 1k data cost : %f ms", [timer timeIntervalSinceNow] * -1000.0);
    NSLog(@"------------------------------------------------");
    [collection waitForWriting];

    [collection clearCache];
```

and if the database has been preloaded with data then starting the app will still consume 200mb to 400mb of memory.  when calling 

``` objective-c
    NyaruDB *db = [NyaruDB instance];
    NyaruCollection *collection = [db collection:@"speed"];
```

I think it try to load it to memory even   "#define NYARU_CACHE_LIMIT 1"

overall, after testing each one of (YapDatabase, NULevelDB,SimpleDB,APLevelDB and even couchbase lite) I still like NyaruDB the best. I think its simplicity in query and statement. Much easier to read

**Comment by kelp404** [comment]
Hello @steve21124 ,

Maybe there are memory issues in this project.
I use NyaruDB in my app, but I didn't get crash reports about memory issues.

NyaruDB is a simple database for iOS.
If you want to put over 1k documents into database, I think you should change the structure of your app.

**Comment by steve21124** [comment]
thanks. though sometimes, for specific case, large database might needed.
