### ISSUE TITLE
ld: 23 duplicate symbols

### ISSUE THREAD

**Issue by lexrus** [kelp404/NyaruDB#2]
Installed through CocoaPods.

Looks like NyaruDB is not compatible with original JSONKit?

![Screen Shot 2013-03-14 at 7 07 45 PM](https://f.cloud.github.com/assets/219689/258425/8f33a95e-8c97-11e2-8d2c-c3d4566d3018.png)

**Comment by kelp404** [comment]
Hi, @lexrus ,

Thank you for submitting this issue.

I add two messages in JSONKit for serializing NSDate, but not rename other classes.
I will clean up JSONKit.
