### ISSUE TITLE
Updating data

### ISSUE THREAD

**Issue by sandsower** [kelp404/NyaruDB#4]
I've searched the documentation but didn't find an answer. Are the objects returned from the fetch array mutables? If not, is it possible to update data without having to delete it?

**Comment by kelp404** [comment]
Hello, @sandsower 

Thank you for submitting this issue.

`[NyaruQuery fetch]` returns `NSArray`, and all objects in the array is `NSMutableDictionary`.
If you insert a document the `key` is exist in the collection, the old document will be replace with the new document.

In this version, update the document you will get a log in debug console, it may be removed in future.

ex1:

``` objective-c
NyaruDB *db = [NyaruDB instance];

NyaruCollection *collection = [db collectionForName:@"collectionName"];
[collection removeAll];
NSMutableDictionary *doc = [collection insert:@{@"email": @"kelp@phate.org", @"name": @"Kelp"}];
// update email
[doc setObject:@"cc@phate.org" forKey:@"email"];
[collection insert:doc];

NSLog(@"%@", collection.all.fetch);
```

ex2:

``` objective-c
NyaruDB *db = [NyaruDB instance];

NyaruCollection *collection = [db collectionForName:@"collectionName"];
[collection removeAll];
[collection insert:@{@"email": @"kelp@phate.org", @"name": @"Kelp"}];
for (NSMutableDictionary *doc in collection.all.fetch) {
    // update email
    [doc setObject:@"cc@phate.org" forKey:@"email"];
    [collection insert:doc];
}

NSLog(@"%@", collection.all.fetch);
```

**Comment by sandsower** [comment]
Thanks for the help! I'm actually having some problems saving/updating complex models. I don't know if it's a bug. For example, this code is what I'm using to save the structure (with data being my model): 

``` Objective-C
    NyaruDB *db = [NyaruDB instance];
    NyaruCollection *collection = [db collectionForName:@"persons"];
    [collection insert:data];
```

An example of the structures I'm dealing with:

``` json
documents: {
    documents =     {
        AppearanceRelease =         [
                        {
                firstName = Nick;
                genre = Male;
                guardians =                 [
                                        {
                        firstName = "Mr.";
                        genre = Male;
                        middleName = "Rivera Martinez";
                        phone = "977-18-51";
                        secondName = Lupillo;
                    },
                                        {
                        firstName = "Ms.";
                        genre = Female;
                        middleName = "Rivera Martinez";
                        phone = "977-18-51";
                        secondName = "Paty.";
                    }
                ];
                key = 8TXLFMPEDPIKC430;
                location =                 {
                    address1 = "Jose Guerra Palos 341";
                    address2 = "Guadalupe Peralta Gamez";
                    city = Aguascalientes;
                    state = Aguascalientes;
                    zipCode = 20277;
                };
                middleName = "Rivera Martinez";
                secondName = "Jr.";
            }
        ];
    };
    key = "A801E38B-BB47-4339-92F4-66692CBDD9C1";
    projectKey = "83E93924-8741-4929-9E7A-65770D66EDBE";
}
```

In this case, the array under the key AppearanceRelease is the one that changes. I say that it might be a bug because if I run the code to retrieve the data in the **same session** as I saved it, **it returns the data with the same structure successfully**. However, if I stop the application and try to retrieve the data (using the same code in both cases), this is what the database returns:

``` json
documents: {
    documents =     {
        AppearanceRelease =         [
        ];
    };
    key = "A801E38B-BB47-4339-92F4-66692CBDD9C1";
    projectKey = "83E93924-8741-4929-9E7A-65770D66EDBE";
}
```

Which, as you can see, holds nothing on under the AppearanceRelease. Perhaps an issue with the way that I'm accessing or saving to the database? Or something to do with caching the information but not saving it? Again, any help will be appreciated.

**Comment by kelp404** [comment]
Hello, @sandsower ,

https://github.com/kelp404/NyaruDB#document

> Normal Field Datatype: NSNull, NSNumber, NSDate, NSString, NSArray, NSDictionary
> **(items just allow NSString, NSNumber, NSDate and NSNull in the NSArray)**

It does not support `NSDictionary`, `NSArray` in `NSArray`.

**Comment by sandsower** [comment]
Thank you for your support!, I'll change the architecture to accomodate this. Is this type of structure going to be supported in the future? Or is this out of scope for the current project?

**Comment by kelp404** [comment]
I am not sure.
I think storing array data in a collection with each documents is better.
